name: ml4sci
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=3.1

  - pandas
  - xarray
  - toolz

  - matplotlib
  - holoviews
  - hvplot
  - bokeh
  - pydot

  - pandas-profiling>=3
  - ipywidgets
  - scikit-learn=1.0.1
  - scikit-image
  - xgboost
  - tensorflow>=2.5
  - keras

  - tensorflow-gpu

  - pip
  - pip:
    - nb-clean
