name: ml4sci
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab

  - pandas
  - xarray
  - toolz

  - matplotlib
  - holoviews
  - hvplot
  - bokeh

  - pandas-profiling>=3
  - ipywidgets
  - scikit-learn
  - scikit-image
  - xgboost
  - tensorflow>=2
  - keras
  - pydot
  - graphviz

  # - tensorflow-gpu
  # - cudatoolkit

  - pip
  - pip:
    - nb-clean
