name: ml4sci
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  
  - pandas
  - xarray
  
  - matplotlib
  - holoviews
  - hvplot
  - bokeh
  
  - pandas-profiling>=3
  - ipywidgets
  - scikit-learn
  - scikit-image
  
  - pip:       
    - nb-clean 
